name: StockAlertApi

on:
  schedule:
    - cron: '0 21 * * 1-5'  # 17h Manaus (21h UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client requests pytz python-dotenv

      - name: Rodar script
        run: python "StockAlertApi3.1.py"
        env:
          GET_NUMWPP_ENV: ${{ secrets.GET_NUMWPP_ENV }}
          GOOGLE_CRED_JSON: ${{ secrets.GOOGLE_CRED_JSON }}
          META_WHATSAPP_TOKEN: ${{ secrets.META_WHATSAPP_TOKEN }}
          META_PHONE_ID: ${{ secrets.META_PHONE_ID }}
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}